version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - run:
          name: build
          command: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: test
          command: npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: audit
          command: npm audit

workflows:
  version: 2
  build:
    jobs:
      - build
      - test
          requires:
            - build
      - analyze
          requires:
            - test